server:
  port: 8082

spring:
  datasource:
    username: root
    password: dag19981108
    url: jdbc:mysql://localhost:3306/MBTest?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
